-- MySQL Script generated by MySQL Workbench
-- Sun Sep 17 17:57:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app1` DEFAULT CHARACTER SET utf8 ;
USE `app1` ;

-- -----------------------------------------------------
-- Table `app1`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`provider` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NOT NULL,
  `provider_phone` INT NOT NULL,
  PRIMARY KEY (`provider_id`),
  UNIQUE INDEX `provider_id_UNIQUE` (`provider_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`order_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`order_provider` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `provider_id` INT NOT NULL,
  `oeder_time` DATE NOT NULL,
  `order_arrived` DATE NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `provider_id_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `provider_id`
    FOREIGN KEY (`provider_id`)
    REFERENCES `app1`.`provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `productc_description` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`order_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`order_contents` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `app1`.`order_provider` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `app1`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`supplies` (
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `app1`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`costumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`costumers` (
  `costumer_id` INT NOT NULL,
  `costumer_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`costumer_id`),
  UNIQUE INDEX `costumer_id_UNIQUE` (`costumer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`stuff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`stuff` (
  `stuff_id` INT NOT NULL AUTO_INCREMENT,
  `stuff_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `work_title` VARCHAR(45) NULL,
  PRIMARY KEY (`stuff_id`),
  UNIQUE INDEX `stuff_id_UNIQUE` (`stuff_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`sales` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `costumer_id` INT NOT NULL,
  `stuff_id` INT NOT NULL,
  `price` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `costumer_id_idx` (`costumer_id` ASC) VISIBLE,
  INDEX `stuff_id_idx` (`stuff_id` ASC) VISIBLE,
  UNIQUE INDEX `sale_id_UNIQUE` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `costumer_id`
    FOREIGN KEY (`costumer_id`)
    REFERENCES `app1`.`costumers` (`costumer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stuff_id`
    FOREIGN KEY (`stuff_id`)
    REFERENCES `app1`.`stuff` (`stuff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app1`.`sale_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app1`.`sale_content` (
  `sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `sale_id_idx` (`sale_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `sale_id`
    FOREIGN KEY (`sale_id`)
    REFERENCES `app1`.`sales` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `app1`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
